name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "phatmap234@gmail.com"
          git config --global user.name "phatmap234"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.gldt-2ov_RwTXvKoAf6Uz-8Cd }}
        run: |
          git remote add gitlab https://oauth2:${{ secrets.gldt-2ov_RwTXvKoAf6Uz-8Cd }}@gitlab.com/phatmap234/shopify-gitlab.git
          git push -u gitlab --all
